version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: electron_crash_report_server
      POSTGRES_PASSWORD: ecrs
    restart: always

  web:
    image: jmuhl/electron-crash-report-server
    depends_on: 
      - db
    environment:
      AUTH_PASS: electron
      AUTH_USER: crash
      DATABASE_URL: postgres://postgres:ecrs@db/electron_crash_report_server
      NODE_ENV: "production"
      PORT: 8080
    ports:
      - "80:8080"
    restart: always
