version: 2

jobs:
  build:
    working_directory: ~/electron-crash-report-server
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn install
          command: |
            yarn global add greenkeeper-lockfile@1
            yarn install
      - run:
          name: yarn test
          command: |
            "`yarn global bin`/greenkeeper-lockfile-update"
            yarn test
            "`yarn global bin`/greenkeeper-lockfile-upload"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
